# Generated by Django 4.0.6 on 2022-07-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('priceDol', models.DecimalField(decimal_places=2, max_digits=8)),
                ('priceRub', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deliveryTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
