# Generated by Django 4.0.6 on 2022-07-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetData', '0002_alter_order_deliverytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.CharField(max_length=10),
        ),
    ]
