# Generated by Django 4.0.6 on 2022-07-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetData', '0003_alter_order_deliverytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='priceDol',
            new_name='priceUSD',
        ),
    ]
