# Generated by Django 4.0.6 on 2022-07-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetData', '0005_remove_order_pricerub_order_ordernumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.CharField(max_length=10, verbose_name='срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='заказ №'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.PositiveIntegerField(verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priceRUB',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='стоимость в руб'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priceUSD',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='стоимость,$'),
        ),
    ]
